### PR TITLE
Update dependencies

### PR DESCRIPTION
**Pull request by carlosjeurissen**
This updates all dependencies to the latest version, except the following:
"execa": "^5.1.1",
"cpy": "^8.1.2",
"rollup": "^2.79.1",
"husky": "^4.3.8",
(mentioned version is the highest version supported with the current setup).

After updating the dependencies the following scripts have been tested and concluded to work:
- module-check
- test
- build

### CODE REVIEW

**Comment by niksy** [comment]
Thank you for the effort, but most of these dependencies will update itself based on minor semver range on install since there is no package lock.

**Comment by carlosjeurissen** [comment]
@niksy Thanks for considering. While some will indeed update themselves based on minor semver. The following would not:
@rollup/plugin-babel
@types/node
core-js
eslint-config-nitpick
eslint-config-prettier
eslint-plugin-prettier
nodemon
np
prettier
stylelint
typescript

**Comment by niksy** [comment]
These are all development dependencies, I would like to keep them that way until I update it upstream in my projects scaffolding tool.

**Comment by carlosjeurissen** [comment]
That makes sense. Thanks for clarifying, making the tool, and merging the other PR! :)

**Pull request closed without merging**
